### ISSUE TITLE
Show an error when user profile is too large

### ISSUE THREAD

**Issue by schancel** [cashweb/stamp#73]
Previously, we showed invalid transaction when the profile avatar was too large.  Now we show nothing except that things don't move forward. Also, there's no indication that a user has to upload an avatar.

This is a terrible user experience, and has left a lot of people stuck at the create profile step without intervention from someone technical.

**Comment by hlb8122** [comment]
Client-side notifications
https://github.com/cashweb/stamp/commit/3850d1030bc1adcc54f921e43a54cd91b8e38ccc
Server-side catching
https://github.com/cashweb/cash-relay/commit/2b23dd3b2d153038b5ad037f311d59ad6421dff2
