### ISSUE TITLE
Notifications now showing up when backgrounded

### ISSUE THREAD

**Issue by schancel** [cashweb/stamp#78]
It seems that when the application window is not in the foreground, but the person talking to you is the active chat, it does not properly notify the user.  We need some way to detect that the window is not foreground, and still provide notifications.

Although... sometimes this does work. Needs more investigation.

**Comment by hlb8122** [comment]
Here's the devil in question
https://github.com/cashweb/stamp/blob/39ac123ae612a8462d0ff2dc5aa062b777d7d845/src/store/modules/chats.js#L666
